name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Docker Image Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}

      - name: Configure Servers with Ansible
        run: ansible-playbook ansible/setup.yaml -i ansible/inventory.ini
